package ali.hrhera.registration_sdk.domain.dto

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * This data class represents a user in the cache.
 *
 * @property id a unique identifier for the user. it is auto-generated by the database.
 * @property name the name of the user.
 * @property email the email of the user. it is unique.
 * @property phoneNumber the phone number of the user. it is unique.
 * @property password the password of the user.
 */
@Entity(
    tableName = "userInfo",
    indices = [Index(value = ["phoneNumber"], unique = true),Index(value = ["email"], unique = true), ]

)
data class UserInfoCachingEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val name: String,
    val email: String,
    val phoneNumber: String,
    val password: String,
)